### ISSUE TITLE
Linux HidDevices.open() error

### ISSUE THREAD

**Issue by iFrez** [vinsfortunato/hid4flutter#11]
Hello, could you please help me with error 

> flutter: HID Exception: Failed to open hid device. Error: Closure: () => String from Function '_getLastErrorMessage@344186600':.()

example of code

>     void _connectToDevice() async {
>     List<HidDevice> devices =
>         await Hid.getDevices(vendorId: 0x1234, productId: 0x1234);
> 
>     devices = devices.where((device) {
>       return device.vendorId == 0x1234&& device.productId == 0x1234;
>     }).toList();
>     try {
>       if (devices.isNotEmpty) {
>         openDevice = devices.first;
>         await openDevice.open();
>         _timer = Timer.periodic(const Duration(milliseconds: 100), (timer) {
>           _readFromDevice();
>         });
>       } else {
>         await Future.delayed(const Duration(seconds: 1));
>         _connectToDevice();
>       }
>     } catch (e) {
>       if (e is HidException) {
>         print('HID Exception: ${e.message}');
>         await Future.delayed(const Duration(seconds: 1));
>         _connectToDevice();
>       } else {
>         print('Unexpected Exception: $e');
>         await Future.delayed(const Duration(seconds: 1));
>         _connectToDevice();
>       }
>     }
>     }
OS: Ubuntu 20.04
Same code on Windows 11 works fine.

**Comment by vinsfortunato** [comment]
Can you please update to 0.1.3? The error message will now give us more information about this issue.

`Error: Closure: () => String from Function '_getLastErrorMessage@344186600':.()` is not supposed to be printed, I fixed this in #13, it will now show you the real error message that caused you issue.

Also now you don't need to do 

```dart
devices = devices.where((device) {
  return device.vendorId == 0x1234&& device.productId == 0x1234;
}).toList();
```

since I've fixed the `Hid.getDevices(...)` method in #12

**Comment by iFrez** [comment]
@vinsfortunato, sure!

> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Operation 'toDartString' not allowed on a 'nullptr'.
> #0      CharPointerToString._ensureNotNullptr (package:hid4flutter/src/desktop/extensions.dart:40)
> #1      WCharPointerToString.toDartString (package:hid4flutter/src/desktop/extensions.dart:48)
> #2      HidDeviceDesktop._getLastErrorMessage (package:hid4flutter/src/desktop/hid_device_desktop.dart:276)
> #3      HidDeviceDesktop.open.<anonymous closure> (package:hid4flutter/src/desktop/hid_device_desktop.dart:94)
> #4      using (package:ffi/src/arena.dart:124)
> #5      HidDeviceDesktop.open (package:hid4flutter/src/desktop/hid_device_desktop.dart:89)
> #6      _MainAppState._connectToDevice (package:testing/main.dart:48)
> <asynchronous suspension>
